#!/usr/bin/env zsh

# https://docs.google.com/presentation/d/1_QmeV3yoDrTvvjDCroOWdhHpvzCtoRUYtq0qmByiYwA/mobilepresent?pli=1&slide=id.ge9895530b7_0_50

set -x

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

source ~/.config/yabai/config/yabai/initialization.sh

# ====
# Signals
# ====

# Initialize the temp folder when adding or removing displays
yabai -m signal --add event=display_added action="~/.config/yabai/config/yabai/initialization.sh"
yabai -m signal --add event=display_removed action="~/.config/yabai/config/yabai/initialization.sh"

yabai -m signal --add event=window_focused action="~/.config/yabai/config/yabai/change-window-border-color-when-window-focused.sh"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="~/.config/yabai/config/yabai/auto-focus-to-new-one-when-window-destroyed.sh 2> /dev/null"

yabai -m signal --add event=application_hidden action="~/.config/yabai/config/yabai/auto-focus-to-new-one-when-window-destroyed.sh 2> /dev/null"
yabai -m signal --add event=window_minimized action="~/.config/yabai/config/yabai/auto-focus-to-new-one-when-window-destroyed.sh 2> /dev/null"

# ====
# Settings
# ====

# yabai -m rule --add app="^neovide$" manage=on

yabai -m config focus_follows_mouse on
yabai -m config window_placement second_child
yabai -m config window_topmost off
yabai -m config window_shadow off

yabai -m config window_border off
yabai -m config window_border_placement inset
yabai -m config window_border_blur off
yabai -m config window_border_hidpi off
yabai -m config window_border_width 0
yabai -m config window_border_radius 0
yabai -m config active_window_border_topmost off
yabai -m config active_window_border_color 0xfcFFEE58
yabai -m config normal_window_border_color 0x00ffffff
yabai -m config insert_window_border_color 0xffd75f5f

yabai -m config window_opacity on
yabai -m config window_opacity_duration .2
yabai -m config active_window_opacity .9
yabai -m config normal_window_opacity .8

yabai -m config split_ratio 0.50
yabai -m config auto_balance off
yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize

yabai -m config layout bsp
yabai -m config top_padding 0
yabai -m config bottom_padding 0
yabai -m config left_padding 0
yabai -m config right_padding 0
yabai -m config window_gap 4

# animation
yabai -m config window_animation_duration 0.30

yabai -m config external_bar all:0:24 \
	mouse_follows_focus off \
	window_zoom_persist off \
	insert_feedback_color 0xff9dd274 \
	auto_padding on \
	mouse_drop_action swap

# ====
# Rules
# ====

otherApp='^(Finder|DBeaver|Calendar|System Preferences|System Settings|Mail|WeChat|WeCom|QQ|Music|网易有道翻译|Input Source Pro|Spotify|预览|scrcpy|文本编辑|Kap|Shottr)$'
yabai -m rule --add app="${otherApp}" manage=off


notOpacityApp='(Chrome|WeCom|WeChat|PDF|Firefox|Arc|Browser|Zed)'
yabai -m rule --add app="${notOpacityApp}" opacity=1

## specific rule

# yabai -m rule --add app="^IntelliJ IDEA$" manage=off
# yabai -m rule --add app="^IntelliJ IDEA$" title="( – )" manage=on

# Exclude problematic apps from being managed:
# yabai -m rule --add app="^(LuLu|Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|App Store|Steam|Alfred|Activity Monitor)$" manage=off
# yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
# yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
# yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
# yabai -m rule --add label="Select file to save to" app="^Inkscape$" title="Select file to save to" manage=off

echo "yabai configuration loaded.."
