#!/bin/sh

width=${2:-80%}
height=${2:-80%}
if [ "$(tmux display-message -p -F "#{session_name}")" = "float-term" ];then
    tmux detach-client
else
    tmux display-popup -d '#{pane_current_path}' -xC -yC -w$width -h$height -E "tmux attach -t float-term || tmux new -s float-term"
fi

