[opener]
edit = [
  { run = 'nvim "$@"', block = true },
  { desc = "neovide", run = '/Applications/Neovide.app/Contents/MacOS/neovide $@', block = true },
]

[manager]
show_hidden = true
linemode = "size"
