wsl = false
no-multigrid = false
vsync = true
maximized = false
srgb = false
idle = true
frame = "none"
title-hidden = true
tabs = true


[font]
normal = ["VictorMono Nerd Font Mono"]
size = 15

# [font.features]
# MonoLisa = [
#   "+ss01",
#   "+ss07",
#   "+ss11",
#   "-calt",
#   "+ss09",
#   "+ss02",
#   "+ss14",
#   "+ss16",
#   "+ss17",
# ]
